### ISSUE TITLE
Implement difference, intersect.

### ISSUE THREAD

**Issue by nilesh-c** [SANSA-Stack/SANSA-RDF#15]
See https://jena.apache.org/documentation/javadoc/jena/org/apache/jena/rdf/model/Model.html for details.

**Comment by patrickwestphal** [comment]
Merged `feature/turtle` to develop. This doesn't solve the task above, but it this done, now @GezimSejdiu ?

**Comment by GezimSejdiu** [comment]
Yes, you are right. 
This does not solve completely the issue above. But the basic implementation of [intersection](https://github.com/SANSA-Stack/SANSA-RDF/blob/develop/sansa-rdf-spark-parent/sansa-rdf-spark-core/src/main/scala/net/sansa_stack/rdf/spark/model/SparkRDDGraphOps.scala#L100) and [difference](https://github.com/SANSA-Stack/SANSA-RDF/blob/develop/sansa-rdf-spark-parent/sansa-rdf-spark-core/src/main/scala/net/sansa_stack/rdf/spark/model/SparkRDDGraphOps.scala#L103 ) was done already, which imply that we can close the issue for now.
