### ISSUE TITLE
review internal table naming

### ISSUE THREAD

**Issue by chile12** [SANSA-Stack/SANSA-RDF#19]
Here:
https://github.com/SANSA-Stack/SANSA-RDF/blob/develop/sansa-rdf-partition-parent/sansa-rdf-partition-sparqlify/src/main/scala/net/sansa_stack/rdf/partition/sparqlify/SparqlifyUtils2.scala#L32

Will trigger an exception when dealing with prefix IRIs not ending with a slash.
I changed it to:

`   val lastSeparatorIndex = Math.max(pred.lastIndexOf("/"), pred.lastIndexOf("#"))
    val tableName = pred.substring(lastSeparatorIndex + 1)`

But it would probably be even better to settle with some less error prone approach all together.

**Comment by Aklakan** [comment]
The more general two questions are:

* What is a nice way to shorten the URIs? For that we could use all prefixes from prefix.cc for starters
* How can we safely encode URIs for spark and flink (the encoding function itself could be passed as a lambda to make the partitioning code independent from flink/spark). For this point I do not know the answer yet - any input would greatly ease our (my :) ) lives.

**Comment by LorenzBuehmann** [comment]
1. Use an URL shortener resp. its algorithm maybe?
2. The most common way should be dictionary encoding or not? Most efficient datatype should be `Int` resp. an `Array[Int]` for triples. Simply using state-of-the-art should work. For example, we could use the JENA API in particular its TDB classes. I've some code somewhere in my workspace to reuse the code.

**Comment by Aklakan** [comment]
We should bundle the table name algo with a copy of known prefixes at http://prefix.cc
This should be a super set of standard prefixes defined by the initial context of RDFa: https://www.w3.org/2011/rdfa-context/rdfa-1.1

**Comment by Aklakan** [comment]
The current table naming strategy will probably still result in clashes;
we should add test cases with predicates having (a) special characters, (b) ending in # and / and (c) have the same local name in different namespaces.

**Comment by Aklakan** [comment]
It seems that spark now properly handles escaped table names.
This means, we now just use the whole URI as a table name; so table naming should be no longer a headache; therefore closing this issue.

We could nonetheless add support for a prefix map as future feature.
