### ISSUE TITLE
Multiple sources found exception

### ISSUE THREAD

**Issue by amgadmadkour** [SANSA-Stack/SANSA-RDF#25]
I get the following exception: `Exception in thread "main" org.apache.spark.sql.AnalysisException: Multiple sources found for ntriples (net.sansa_stack.rdf.spark.io.ntriples.NTriplesDataSource, net.sansa_stack.inference.spark.data.loader.sql.NTriplesDataSource), please specify the fully qualified class name` 

The exception is thrown whenever a project includes both the `SANSA-core` and the  `SANSA-inference` package. To recreate the exception, (e.g. using the Sansa stack template) run the following two lines:

`val lang: Lang = Lang.NTRIPLES`
`var df = spark.read.rdf(lang)(INPUTFILE)`

The redundant datasource is `NTriplesDataSource` as stated in the error.  Im assuming the same error will also be raised for the turtle format. The error is caused due to the same datasource  shortname (e.g. ntriples) being used with the same class name in two different packages. My work-around was to call only one JAR in the project (e.g. SANSA-core).

**Comment by GezimSejdiu** [comment]
Hi @amgadmadkour ,
many thanks for your valuable feedback on this issue. Yes, you are right, I just tested it out and got the same error. This is due multiple sources defined on both layers ([RDF layer](https://github.com/SANSA-Stack/SANSA-RDF/blob/develop/sansa-rdf-spark-parent/sansa-rdf-spark-core/src/main/scala/net/sansa_stack/rdf/spark/io/ntriples/NTriplesDataSource.scala) and [Inference layer](https://github.com/SANSA-Stack/SANSA-Inference/blob/develop/sansa-inference-spark/src/main/scala/net/sansa_stack/inference/spark/data/loader/sql/NTriplesDataSource.scala) ), we are working towards aligning SANSA-Inference reader into SANSA-RDF. It will happen soon:). Will update when it is done.

Best regards,
Gezim

**Comment by LorenzBuehmann** [comment]
Should have been solved with commit https://github.com/SANSA-Stack/SANSA-Inference/commit/79d2b58febfbecf74d846c925bdb60a4bdbbf6ff
