### ISSUE TITLE
Upgrade SANSA-RDF to use Dataset instead of RDD

### ISSUE THREAD

**Issue by amgadmadkour** [SANSA-Stack/SANSA-RDF#26]
Are there plans to upgrade functions of SANSA-RDF to use Dataset[Triple] instead of RDD[Triple] ? 

I see that you are using Kyro to mitigate the large sizes of RDD's at the moment. I also see that you have a wrapper that creates triples as Dataframes at the moment as a middle-ground between RDD's and Datasets. However, [one article](https://databricks.com/blog/2016/07/14/a-tale-of-three-apache-spark-apis-rdds-dataframes-and-datasets.html) illustrates the efficiency of Dataset over RDD's. I think this will be really beneficial for people using Spark 1.6+ and want to interplay with SANSA and avoid the transformation step (RDD->Dataset) everytime when calling a function in SANSA-RDF. Iv personally forked and iv started to upgrade minor functions so that i can continue working with the triples generated by SANSA as Dataset[Triple]. I can make a pull request once i have something done if you guys are open for it.  

Also, do you accept (pull requests/contributions) for new features/upgrades from outside your group ?

**Comment by JensLehmann** [comment]
We are very open to contributions outside of our group. It would be great if you can create a PR which we can then review and ideally incorporate in our code base. Thanks a lot for your feedback and contributions!

**Comment by amgadmadkour** [comment]
I believe with regards to the upgrade issue, the best course of action would be to incrementally create Dataset wrappers for the RDD-specific functions. This would retain RDD functions for low-level usages within SANSA while app developers (Spark 1.6+) can utilize the wrappers.
