### ISSUE TITLE
sparql DSL

### ISSUE THREAD

**Issue by antonkulaga** [SANSA-Stack/SANSA-RDF#32]
It would be quite useful to interact with SPARQL in a type-safe way, maybe it is possible to make sparkq"" interpolation to check that sparql I write is valid or some DSL? Making queries in just strings is not that pleasant...

**Comment by Aklakan** [comment]
Do you mean something like the Java Persistence API over SPARQL?
Would something like our [https://github.com/SmartDataAnalytics/jena-sparql-api/tree/master/jena-sparql-api-mapper](Jena SPARQL API Java/RDF Mapper) fit your needs?
