### ISSUE TITLE
Permissive RDF Parsing (N-Triples)

### ISSUE THREAD

**Issue by Aklakan** [SANSA-Stack/SANSA-RDF#42]
Jena's parser are quite strict when it comes to lexical errors (related to the Tokenizer) and syntactic errors (related to the Parser) in RDF input. Sansa uses the N-Triples parser because it is easy to partition. The purpose of this issue is to improve the existing Jena tooling to be more permissive/forgiving so that problems with the input are reported to the error callbacks - without the parsing process bailing out completely.

**Comment by SimonBin** [comment]
part of https://github.com/SANSA-Stack/SANSA-RDF/tree/feature/fast-rdf-parse
