### ISSUE TITLE
publish latest version

### ISSUE THREAD

**Issue by antonkulaga** [SANSA-Stack/SANSA-RDF#45]
The current published version (0.3.0) is outdated and its API is partially different from latest version and docs.

**Comment by GezimSejdiu** [comment]
Hi @antonkulaga ,

in SANSA we do have a release every six months, which mean the next release (`0.4.0`) will be published during June 2018. 

In case you are using SANSA, and want to experiment with the latest API changes, you are free to use our SNAPSHOTS as well (e.g `0.3.1-SNAPSHOT`), which they are or at least we try to keep them build error free :)).

We will announce the new release via our communication channels and on our respective layers via release notes including all the API changes and dependency changes.

Yes, you are right, some of the docs are not updated to the new changes, and we will align them with all the changes we made during this period of time.

Feel free to ask any futher questions.

Best,

**Comment by antonkulaga** [comment]
Guys, it is already June. Could you please release a version for Spark 2.3.1? I am tired of building from source.

**Comment by JensLehmann** [comment]
We will probably do this next week.
