### ISSUE TITLE
Signature of net.sansa_stack.rdf.spark.partition.semantic.RdfPartition not clear

### ISSUE THREAD

**Issue by patrickwestphal** [SANSA-Stack/SANSA-RDF#68]
To instantiate `RdfPartition` one has to pass the parameter [`partitionedDataPath` ](https://github.com/SANSA-Stack/SANSA-RDF/blob/develop/sansa-rdf-spark/src/main/scala/net/sansa_stack/rdf/spark/partition/semantic/RdfPartition.scala#L17) which is not explained, nor used anywhere. It is also used in the [SANSA-Examples](https://github.com/SANSA-Stack/SANSA-Examples/blob/develop/sansa-examples-spark/src/main/scala/net/sansa_stack/examples/spark/query/Semantic.scala#L149-L151) without further explanation. Wondering whether it could be dropped.

**Comment by GezimSejdiu** [comment]
Hi @patrickwestphal ,

many thanks for the question! Indeed, we could drop it as it is not needed on our implementation. It was there and used by Imran just for some evaluation after I guided him to get rid of the partitioning paths. I will remove it from the original code and update SANSA-Examples accordingly. 

Best,
