### ISSUE TITLE
Merge graph-analysis into graph.model

### ISSUE THREAD

**Issue by GezimSejdiu** [SANSA-Stack/SANSA-RDF#77]
We should consider merging [graph-analysis implementation](https://github.com/SANSA-Stack/SANSA-RDF/tree/feature-claus-shortest-paths/src/main/scala/org/dissect/rdf/spark/analytics) into our [graph.model](https://github.com/SANSA-Stack/SANSA-RDF/tree/develop/sansa-rdf-spark/src/main/scala/net/sansa_stack/rdf/spark/model/graph) implementation in case we want to offer these functionalities into SANSA.

Best regards,

**Comment by Aklakan** [comment]
I need to try out whether the code in this branch is (a) still compiling, (b) doing anything useful

**Comment by Aklakan** [comment]
Deleted branch
