### ISSUE TITLE
Can not build the project

### ISSUE THREAD

**Issue by purohitsumit** [SANSA-Stack/SANSA-RDF#88]
Hi @LorenzBuehmann :  Following instructions from http://sansa-stack.net/downloads-usage/ "Using SANSA in Maven Projects", i get following error: 
`Failed to collect dependencies at net.sansa-stack:sansa-rdf-spark_2.11:jar:0.6.0 -> com.ibm.sparktc.sparkbench:sparkbench:jar:2.3.0_0.4.0: Failed to read artifact descriptor for com.ibm.sparktc.sparkbench:sparkbench:jar:2.3.0_0.4.0:  `
I see that the dependency has been removed in the latest commit by you. Is there a plan to push it to maven central ?

Thanks

**Comment by GezimSejdiu** [comment]
Hi @purohitsumit ,

thanks a lot for the issue. I saw that you were able to overcome this issue by using our (pre-stable) SNAPSHOT release `0.6.1-SNAPSHOT`. 

Maven Central doesn't allow overriding existing published version, therefore there is a need to publish another minor version to fix the issue. 
We plan to release **SANSA 0.7** mid-December which fixes this issue. Until then, you can use our latest SNAPSHOT release.

We can keep the issue open until we release **SANSA 0.7** version, or if you like -- feel free to close it as the fixes will come with the release.

Best regards,

**Comment by JensLehmann** [comment]
The 0.7 release is tentatively scheduled for December 16th. Is it fine that we fix it then?

**Comment by LorenzBuehmann** [comment]
Issue has been resolved with 0.7 release.
