### ISSUE TITLE
Value rdf is not a member of SparkSession

### ISSUE THREAD

**Issue by GiorgosMandi** [SANSA-Stack/SANSA-RDF#96]
Hello,
I try to use sansa-rdf-spark to load a distributed NTRIPLES dataset as RDD.
So i mported the library by adding the following dependency in my build.sbt file 
	
	// https://mvnrepository.com/artifact/net.sansa-stack/sansa-rdf-spark  
	libraryDependencies += "net.sansa-stack" %% "sansa-rdf-spark" % "0.7.1"	
and then I tried the following code:

	import net.sansa_stack.rdf.spark.io._  
	import org.apache.jena.riot.Lang  
	import org.apache.spark.sql.SparkSession  
	  
	val spark: SparkSession = SparkSession.builder().getOrCreate()  
	val lang = Lang.NTRIPLES  
	val triples = spark.rdf(lang)(filePath)  
	triples.take(5).foreach(println(_))
However, it fails to compile with the error
		
	Error:(X, Y) value rdf is not a member of org.apache.spark.sql.SparkSession
			 triples = spark.rdf(lang)(filePath) 
Do you know how can I fix it?
Thanks in advance

**Comment by LorenzBuehmann** [comment]
Hi,
I can't reproduce this error.
I tried with a fresh SBT project just containg Spark 2.4.5 core and sql as well as sansa-rdf-spark 0.7.1 dependencies:

```sbt
val sparkVersion = "2.4.5"

scalaVersion := "2.11.12"

libraryDependencies ++= Seq(
  "net.sansa-stack" %% "sansa-rdf-spark" % "0.7.1",
  "org.apache.spark" %%  "spark-core" % sparkVersion,
  "org.apache.spark" %%  "spark-sql" % sparkVersion
)
```
is it possible that you have some older SANSA dependencies in your project as well?

**Comment by GiorgosMandi** [comment]
After some experimentation, I found that the error was produced because I had named my Object class as RDFReader, which is the same name as the implicit class.

Thanks :)
